version: '3.8'

services:
  backend-api:
    container_name: user-manager-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=data/users.db
      - Jwt__Key=54cf09d95836502a2881ffb336643f96!
      - Jwt__Issuer=backend-api
      - Jwt__Audience=angular-app
    volumes:
      - ./data:/app/data
    restart: always

  frontend:
    container_name: user-manager-web
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend-api
    restart: always
